# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Gonzalo Rodríguez-Baltanás Díaz
email: gonzalo.rodriguez@nerian.es
description: Personal website of Gonzalo Rodríguez-Baltanás Díaz.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://nerian.es" # the base hostname & protocol for your site
twitter_username: icodeergoxist
github_username:  Nerian

# Build settings
markdown: kramdown

disqus:
  shortname: nerian-blog

exclude:
  - Gemfile
  - Gemfile.lock
  - project.mobirise
  - post.thor