inc:
  # Blog Information
  title:        "Gonzalo Rodríguez-Baltanás Díaz"
  subtitle:     "Professional Web Development with Ruby on Rails"
  cover_image:  main_cover.png
  logo:         logo.png

  # Company information
  company:      "Gonzalo Rodríguez-Baltanás Díaz"
  url:          http://nerian.es
  facebook:
  twitter:      iCodeErgoExist
  gplus:        ''
  about_link:   ''

  # Product Information
  product_link: http://nerian.es
  tagline:      "Web Development the way is meant to be done"

  # Comments
  disqus:
    # Eg. "exampleblog" Set to false to disable comments
    shortname: nerian-blog

  # Sharing settings
  sharing:
    twitter:    true
    facebook:   true
    gplus:      true
    hn:         true


 # Analytics
  analytics:
    google:
      # eg. 'UA-123-12'
      id:    'UA-43311904-1'


  # Google Fonts
  # eg. 'Droid+Sans:400,700|Droid+Serif:400,700'
  # google_font: 'Merriweather:400|Open Sans:600'
  google_font: ''

  # Setup your fonts, colors etc at _assets/stylesheets/main.scss

url:         http://nerian.es
source:      .
destination: ./_site
plugins_dir:     ./_plugins
layouts_dir:     ./_layouts
include:     ['.htaccess']
exclude:     []
timezone:    nil

# Show future posts
future:      false
show_drafts: nil
limit_posts: 0
highlighter: pygments

permalink:     pretty
paginate_path: 'page/:num'
paginate: 5

markdown:      kramdown
markdown_ext:  markdown,mkd,mkdn,md
textile_ext:   textile

excerpt_separator: "<!-- more -->"

safe:        false
host:        0.0.0.0
port:        4000
baseurl:     /
lsi:         false

maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex

rdiscount:
  extensions: []

redcarpet:
  extensions: []

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  wrap: div
  line_numbers: inline
  line_numbers_start: 1
  tab_width: 4
  bold_every: 10
  css: style

redcloth:
  hard_breaks: true

#
# jekyll-assets: see more at https://github.com/ixti/jekyll-assets
#
assets:

  dirname: assets
  baseurl: /assets/
  sources:
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/images
  js_compressor: uglifier
  css_compressor: sass
  cache_type: memory
  gzip: [ text/css, application/javascript ]
  debug: false

gems:
  - jekyll-redirect-from
  - jekyll-paginate