source 'https://rubygems.org'

gem 'jekyll'
gem 'jekyll-assets'
# gem 'maruku'
gem 'rake'
gem 'sass'
gem 'uglifier'
gem 'github-pages'
gem 'kramdown'
gem 'activesupport'
gem 'thor'
gem 'jekyll-redirect-from'
gem 'jekyll-paginate'
gem 'pygments.rb'